CREATE TABLE TBL_USER
(
	USER_ID VARCHAR2(50) NOT NULL,
	USER_PW VARCHAR2(150) NOT NULL,
	USER_NAME VARCHAR2(20) NOT NULL,
	USER_GENDER VARCHAR2(20) NOT NULL,
	USER_BIRTH DATE NOT NULL,
	WALK_DAY VARCHAR2(50) NOT NULL,
	WALK_TIME VARCHAR2(20) NOT NULL,
	WALK_HOUR NUMBER(2) NOT NULL,
	WALK_MINUTE NUMBER(2) NOT NULL,
	WALK_PLACE1 VARCHAR(200) NOT NULL,
	WALK_PLACE2 VARCHAR(200),
	WALK_STYLE VARCHAR(1000),
	CONSTRAINT USER_PK PRIMARY KEY(USER_ID)
);

DELETE FROM TBL_USER;
DELETE FROM TBL_BOARD tb ;

SELECT * FROM TBL_USER;
SELECT * FROM TBL_WALK tw ;

ALTER TABLE TBL_PET ADD SI VARCHAR(100);
ALTER TABLE TBL_PET ADD GUNGU VARCHAR(100);
ALTER TABLE TBL_PET ADD DONG VARCHAR(100);


CREATE SEQUENCE SEQ_PET;
--
--INSERT INTO HR.TBL_USER
--(USER_ID, USER_PW, USER_NAME, USER_GENDER, USER_BIRTH, WALK_DAY, WALK_TIME, WALK_HOUR, WALK_MINUTE, WALK_PLACE1, WALK_PLACE2, WALK_STYLE)
--VALUES('dfds', 'sdf', 'sdf', 'df', TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'sf', 'df', 0, 0, 'df', 'fd', 'fd');
SELECT TO_CHAR("DATE", 'MM/DD') "DATE" FROM TBL_WALK WHERE NUM>0 AND ROWNUM BETWEEN 1 AND 20 ORDER BY NUM DESC, REG_DATE DESC;

INSERT INTO HR.TBL_WALK
(NUM, USER_ID, TITLE, LOCATION, "DATE", WALK_TIME, WALK_HOUR, WALK_MINUTE, CONTENT, REG_DATE, THUMB, AGE, BREED)
VALUES(SEQ_WALK.NEXTVAL, 'akdlwb33', '산책가요', '송도 달빛 축제 공원', TIMESTAMP '2021-06-24 00:00:00.000000', '오전', 2, 30, 'ㅎㅇㅁㅎㅎㅁ', TIMESTAMP '2021-06-11 11:17:49.000000', '\imgUpload\2021\06\10\s\s_c354d78d-5ef5-404b-ae4c-bb304019e660_캡처.PNG', 1, '골든 리트리버');


CREATE TABLE TBL_PET(
	PET_NUM NUMBER(10) NOT NULL,	
	USER_ID VARCHAR2(50) NOT NULL,
	PET_PHOTO VARCHAR2(200),
	PET_PHOTOTHUMB VARCHAR(200),
	PET_NAME VARCHAR2(20) NOT NULL,
	PET_AGE NUMBER(3) NOT NULL,
	PET_GENDER VARCHAR2(20) NOT NULL,
	PET_BREED VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(50) NOT NULL,
	PET_WEIGHT NUMBER(10) NOT NULL,
	SURGERY VARCHAR2(10) NOT NULL,
	LIKES VARCHAR2(200) NOT NULL,
	DISLIKES VARCHAR2(200) NOT NULL,
	CHARACTER1 VARCHAR2(20) NOT NULL,
	CHARACTER2 VARCHAR2(20),
	CHARACTER3 VARCHAR2(20),
	TIP VARCHAR2(1000),
	CONSTRAINTS PET_PK PRIMARY KEY(PET_NUM),
	CONSTRAINT PET_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

ALTER TABLE TBL_PET ADD PET_PHOTOTHUMB VARCHAR(200);

SELECT
			NUM, 
			USER_ID, 
			TITLE, 
			LOCATION, 
			TO_CHAR("DATE", 'MM/DD') "DATE", 
			WALK_TIME, 
			WALK_HOUR, 
			WALK_MINUTE, 
			CONTENT,
			REG_DATE,
			THUMB,
			AGE,
			BREED
			FROM TBL_WALK WHERE NUM <= 16 AND NUM > 16-20 ORDER BY NUM DESC, REG_DATE DESC;

CREATE SEQUENCE SEQ_WALK;

CREATE TABLE TBL_WALK(
	NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(150) NOT NULL,
	LOCATION VARCHAR2(100) NOT NULL,
	"DATE" DATE NOT NULL,
	WALK_DAY VARCHAR2(50) NOT NULL,
	WALK_HOUR NUMBER(2) NOT NULL,
	WALK_MINUTE NUMBER(2) NOT NULL,
	CONTENT VARCHAR2(500) NOT NULL,
	CONSTRAINTS WALK_PK PRIMARY KEY(NUM),
	CONSTRAINTS WALK_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);
DELETE FROM TBL_WALK tw2;
SELECT * FROM TBL_WALK tw; 
ALTER TABLE TBL_WALK ADD REG_DATE DATE;
ALTER TABLE TBL_WALK ADD THUMB VARCHAR(200);
ALTER TABLE TBL_WALK ADD AGE NUMBER(3);
ALTER TABLE TBL_WALK ADD BREED VARCHAR(100);

SELECT * FROM TBL_WALK WHERE NUM>0 AND ROWNUM BETWEEN 1 AND 20 ORDER BY NUM DESC, REG_DATE DESC;

--SELECT W.*, P.PET_PHOTO FROM TBL_WALK W JOIN TBL_PET P ON W.USER_ID = P.USER_ID;



CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
	NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	CONTENT VARCHAR2(50) NOT NULL,
	LIKE_CNT NUMBER(5),
	"DATE" DATE NOT NULL,
	TYPE VARCHAR2(20) NOT NULL,
	"FILE" VARCHAR2(20),
	CONSTRAINT BOARD_PK PRIMARY KEY(NUM),
	CONSTRAINT BOARD_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

ALTER TABLE TBL_BOARD ADD USER_NAME VARCHAR(100);
ALTER TABLE TBL_BOARD ADD LIKECHECK NUMBER(1);
ALTER TABLE TBL_BOARD MODIFY LIKECHECK NUMBER(1) DEFAULT 0;


SELECT * FROM TBL_BOARD tb ;

CREATE SEQUENCE SEQ_COMMENT;

CREATE TABLE TBL_COMMENT(
	NUM NUMBER(10) NOT NULL,
	BOARD_NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	CONTENT VARCHAR2(40) NOT NULL,
	"DATE" DATE NOT NULL,
	CONSTRAINTS COMMENT_PK PRIMARY KEY(NUM),
	CONSTRAINTS COMMENT_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

ALTER TABLE TBL_COMMENT ADD ADDRESS VARCHAR(100);
ALTER TABLE HR.TBL_COMMENT MODIFY CONTENT VARCHAR2(1000);

CREATE SEQUENCE SEQ_PETPAL;

CREATE TABLE TBL_PETPAL(
	NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	PETPAL_ID VARCHAR2(20) NOT NULL,
	CONSTRAINTS PETPAL_PK PRIMARY KEY(NUM),
	CONSTRAINTS PETPAL_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID),
	CONSTRAINTS PETPAL_FK2 FOREIGN KEY(PETPAL_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE SEQUENCE SEQ_WALKLIKE;

CREATE TABLE TBL_WALK_LIKE(
	NUM NUMBER(10) NOT NULL,
	BOARD_NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	LIKECHECK NUMBER(1),
	CONSTRAINTS WALK_LIKE_PK PRIMARY KEY(NUM),
	CONSTRAINTS WALK_LIKE_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);


SELECT * FROM TBL_COM_LIKE;

CREATE SEQUENCE SEQ_COMLIKE;

CREATE TABLE TBL_COM_LIKE(
	NUM NUMBER(10) NOT NULL,
	BOARD_NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	LIKECHECK NUMBER(1),
	CONSTRAINTS COM_LIKE_PK PRIMARY KEY(NUM),
	CONSTRAINTS COM_LIKE_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE SEQUENCE SEQ_COMSCRAP;

CREATE TABLE TBL_COM_SCRAP(
	NUM NUMBER(10) NOT NULL,
	BOARD_NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	LIKECHECK NUMBER(1),
	CONSTRAINTS COM_SCRAP_PK PRIMARY KEY(NUM),
	CONSTRAINTS COM_SCRAP_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);