CREATE TABLE TBL_USER
(
	USER_ID VARCHAR2(20) NOT NULL,
	USER_PW VARCHAR2(20) NOT NULL,
	USER_NAME VARCHAR2(10) NOT NULL,
	USER_GENDER VARCHAR2(5) NOT NULL,
	USER_BIRTH DATE NOT NULL,
	WALK_DAY VARCHAR2(5) NOT NULL,
	WALK_TIME VARCHAR2(5) NOT NULL,
	WALK_HOUR NUMBER(2) NOT NULL,
	WALK_MINUTE NUMBER(2) NOT NULL,
	WALK_PLACE1 VARCHAR(20) NOT NULL,
	WALK_PLACE2 VARCHAR(20),
	WALK_STYLE VARCHAR(30),
	CONSTRAINT USER_PK PRIMARY KEY(USER_ID)
);

DELETE FROM TBL_USER;
DELETE FROM TBL_PET;

SELECT * FROM TBL_USER;
SELECT * FROM TBL_PET;

CREATE SEQUENCE SEQ_PET;
--
--INSERT INTO HR.TBL_USER
--(USER_ID, USER_PW, USER_NAME, USER_GENDER, USER_BIRTH, WALK_DAY, WALK_TIME, WALK_HOUR, WALK_MINUTE, WALK_PLACE1, WALK_PLACE2, WALK_STYLE)
--VALUES('dfds', 'sdf', 'sdf', 'df', TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'sf', 'df', 0, 0, 'df', 'fd', 'fd');


CREATE TABLE TBL_PET(
	PET_NUM NUMBER(10) NOT NULL,	
	USER_ID VARCHAR2(20) NOT NULL,
	PET_PHOTO VARCHAR2(20),
	PET_NAME VARCHAR2(20) NOT NULL,
	PET_AGE NUMBER(3) NOT NULL,
	PET_GENDER VARCHAR2(10) NOT NULL,
	PET_BREED VARCHAR2(20) NOT NULL,
	ADDRESS VARCHAR2(20) NOT NULL,
	PET_WEIGHT NUMBER(5) NOT NULL,
	SURGERY VARCHAR2(10) NOT NULL,
	LIKES VARCHAR2(20) NOT NULL,
	DISLIKES VARCHAR2(20) NOT NULL,
	CHARACTER1 VARCHAR2(20) NOT NULL,
	CHARACTER2 VARCHAR2(10),
	CHARACTER3 VARCHAR2(10),
	TIP VARCHAR2(30),
	CONSTRAINTS PET_PK PRIMARY KEY(PET_NUM),
	CONSTRAINT PET_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE SEQUENCE SEQ_WALK;

CREATE TABLE TBL_WALK(
	NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(30) NOT NULL,
	LOCATION VARCHAR2(20) NOT NULL,
	"DATE" DATE NOT NULL,
	WALK_DAY VARCHAR2(5) NOT NULL,
	WALK_HOUR NUMBER(2) NOT NULL,
	WALK_MINUTE NUMBER(2) NOT NULL,
	CONTENT VARCHAR2(40) NOT NULL,
	CONSTRAINTS WALK_PK PRIMARY KEY(NUM),
	CONSTRAINTS WALK_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

SELECT * FROM TBL_WALK;

CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
	NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	CONTENT VARCHAR2(50) NOT NULL,
	LIKE_CNT NUMBER(5),
	"DATE" DATE NOT NULL,
	TYPE VARCHAR2(20) NOT NULL,
	"FILE" VARCHAR2(20),
	CONSTRAINT BOARD_PK PRIMARY KEY(NUM),
	CONSTRAINT BOARD_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE SEQUENCE SEQ_COMMENT;

CREATE TABLE TBL_COMMENT(
	NUM NUMBER(10) NOT NULL,
	BOARD_NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	CONTENT VARCHAR2(40) NOT NULL,
	"DATE" DATE NOT NULL,
	CONSTRAINTS COMMENT_PK PRIMARY KEY(NUM),
	CONSTRAINTS COMMENT_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID)
);

CREATE SEQUENCE SEQ_PETPAL;

CREATE TABLE TBL_PETPAL(
	NUM NUMBER(10) NOT NULL,
	USER_ID VARCHAR2(20) NOT NULL,
	PETPAL_ID VARCHAR2(20) NOT NULL,
	CONSTRAINTS PETPAL_PK PRIMARY KEY(NUM),
	CONSTRAINTS PETPAL_FK FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID),
	CONSTRAINTS PETPAL_FK2 FOREIGN KEY(PETPAL_ID) REFERENCES TBL_USER(USER_ID)
);
